### ISSUE TITLE
Jumping to body of function

### ISSUE THREAD

**Issue by dele454** [draffter/FollowFunctionPHP#2]
I tried activating a lookup to the jump to the function body of a highlighted/declared function. But it doesnt seem to work for me.

What do you mean by "Now, you can use plugin, by clicking two times button2 holding Ctrl+Shift on function name."

What is button2??

**Comment by draffter** [comment]
Hi!

After indexing you have to hold Ctrl+Shift and click 2 times (doubleclick) of right mouse button.
